"""empty message

Revision ID: 688954886c04
Revises: 96c565a1f8ac
Create Date: 2023-05-09 09:59:49.651359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688954886c04'
down_revision = '96c565a1f8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healer')
    # ### end Alembic commands ###
